services:
  frontend:
    build: 
      context: ./Frontend/
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
  backend:
    build: 
      context: ./Backend/
      dockerfile: Dockerfile
    ports: 
      - "5000:80"